### ISSUE TITLE
Radar Overlays Warning Polygons

### ISSUE THREAD

**Issue by AnnWX** [SteepAtticStairs/AtticRadar#1]
When the program is in use the radar overlaps the warning polygons can you make sure the warning polygons are above the radar thanks. ![Screenshot 2022-11-29 12 49 26 PM](https://user-images.githubusercontent.com/86276545/204605744-9a440195-997e-4592-bd9d-95937cac41f1.png)

**Comment by SteepAtticStairs** [comment]
Thanks for opening the issue! I'm aware of this, and I'll be able to fix it pretty quickly when I get home later. In the meantime, you can get the polygons to be above the radar by initializing the alerts _after_ rendering a radar's data.

**Comment by SteepAtticStairs** [comment]
This has been fixed as of #f023859

**Comment by SteepAtticStairs** [comment]
This is now fixed with [f023859](https://github.com/SteepAtticStairs/AtticRadar/commit/f023859c4d2eb77089b32b2dd4d0ac1d9f6880c2).
