### ISSUE TITLE
Pen Tool

### ISSUE THREAD

**Issue by AnnWX** [SteepAtticStairs/AtticRadar#3]
I am wondering if you can add a pen tool like in radar scope to AtticRadar.

also do you have an email i can use instead so i don't clog up issues with requests thanks.

**Comment by SteepAtticStairs** [comment]
This is certainly something I intend to add in the future, along with a distance measurement tool.

Currently, I'm redoing the alerts system, and adding an auto updater. But those two things I mentioned at the start of this message will come next.

A good email to reach me at is steepatticstairs@gmail.com.

Thanks for the issue!

**Comment by SteepAtticStairs** [comment]
This will now be tracked at issue #5. See comment the comment [here](https://github.com/SteepAtticStairs/AtticRadar/issues/5#issuecomment-1575316060).
