### ISSUE TITLE
Lightning

### ISSUE THREAD

**Issue by SteepAtticStairs** [SteepAtticStairs/AtticRadar#6]
Continuing the discussion from [`bb45b11`](https://github.com/SteepAtticStairs/AtticRadar/commit/bb45b11ef4ffccbd0ec6c1f3a565571e365e4b19#commitcomment-115656345) and [`56826ce`](https://github.com/SteepAtticStairs/AtticRadar/commit/56826ce2e438343fd9fe0e3c5f47a1fc57309dfb#commitcomment-116356172).

Right now, we're working on making sure that the lightning icons are visible enough. Possibly by increasing the size when zooming in. I can also make the opacity gradient less severe.

**Comment by SteepAtticStairs** [comment]
@wilburcoding With the commit [`bd093fc`](https://github.com/SteepAtticStairs/AtticRadar/commit/bd093fcf522bee6347b84374c5873cf924c74097), the lightning icons are slightly bigger, they increase with the zoom level, and they won't do collision checks at high zoom levels. Also, the opacity scale for older strikes is less severe.

Let me know what you think.

**Comment by wilburcoding** [comment]
So...Would like to apologize for not being clearer. 
Wanted the opacity to be a bit higher but I feel like the previous size was fine.
Again, sorry for not making this clearer.

**Comment by wilburcoding** [comment]
Could you make the difference between old and new strikes more obvious?

**Comment by SteepAtticStairs** [comment]
I like the new size, I think it makes them easier to see.

I found that being more obvious with changing the opacity to differentiate between old and new strikes makes the older ones harder to see. What do you think?

**Comment by wilburcoding** [comment]
Upon zooming in further, I do find the new size better. Still think a slight nudge smaller would be good. 
I feel like changing the opacity to differentiate between old and new strikes should be fine because most people focus on newer strikes and not old ones.

**Comment by SteepAtticStairs** [comment]
Makes sense. What do you think about [`ab92d08`](https://github.com/SteepAtticStairs/AtticRadar/commit/ab92d08bd311fd46860866e3990533526ec0bf6f)?

**Comment by wilburcoding** [comment]
Looks good!

**Comment by SteepAtticStairs** [comment]
Great!

I'll leave the issue open for a couple more days, to see how I feel after I've used it for a bit.

**Comment by SteepAtticStairs** [comment]
Closing for now, because I've been satisfied with it so far.
